### ISSUE TITLE
How to configure public access via https

### ISSUE THREAD

**Issue by nicolaibaralmueller** [geerlingguy/tower-operator#29] opened 2020-03-12 10:37 UTC
Hi Jeff,

How do you configure kubernetes to enable remote access to awx via https.

All pods are running and enabled ingress but have no access to the webite either by port 80 or 443.

Many thanks for your time

**Comment by geerlingguy** [comment] 2020-03-12 17:26
@nicolaibaralmueller - Please see https://github.com/geerlingguy/tower-operator/issues/13 — basically, it's not supported 'out of the box' at this time but you may be able to get HTTPS working by managing the ingress on your own.

You should be able to access Tower/AWX on port 80, though, using whatever you set via `tower_hostname`, assuming `tower_hostname` is properly pointed at your Kubernetes cluster and you have an ingress controller already running and working...

**Comment by geerlingguy** [comment] 2020-03-12 17:27
Closing as duplicate of #13

**Closed as completed by geerlingguy** 2020-03-12 17:27 UTC
Labels: duplicate
